#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_logout:
  path: '/logout'
about:
  path: /about
  controller: App\Controller\ContactController::contactAction

#_errors:
 # resource: '@TwigBundle/Resources/config/routing/errors.xml'
  #prefix:   /_error