# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

    default_mail_recipient:             'contact@letzswap.lu'
    default_mail_sender:                'no-reply@letzswap.lu'

    contact_mail_html_template:         'Contact/contact-mail.html.twig'
    contact_mail_txt_template:          'Contact/contact-mail.txt.twig'

    registration_mail_html_template:    'Registration/registration-mail.html.twig'
    registration_mail_txt_template:     'Registration/registration-mail.txt.twig'

    swap_mail_html_template:            'Swap/swap-mail.html.twig'
    swap_mail_txt_template:             'Swap/swap-mail.txt.twig'

    upload_directory:                   '%kernel.root_dir%/../var/uploads/'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Mailer\Mailer:
        arguments:
            $defaultRecipient:          '%default_mail_recipient%'
            $defaultSender:             '%default_mail_sender%'
            $htmlContactTemplate:       '%contact_mail_html_template%'
            $txtContactTemplate:        '%contact_mail_txt_template%'
            $htmlRegistrationTemplate:  '%registration_mail_html_template%'
            $txtRegistrationTemplate:   '%registration_mail_txt_template%'
            $htmlSwapTemplate:          '%swap_mail_html_template%'
            $txtSwapTemplate:           '%swap_mail_txt_template%'
